/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExamplesBrandlensRouteImport } from './routes/examples.brandlens'
import { Route as PrinciplesNegativeSpaceProgrammingRouteImport } from './routes/principles.negative-space-programming'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesBrandlensRoute = ExamplesBrandlensRouteImport.update({
  id: '/examples/brandlens',
  path: '/examples/brandlens',
  getParentRoute: () => rootRouteImport,
} as any)
const PrinciplesNegativeSpaceProgrammingRoute =
  PrinciplesNegativeSpaceProgrammingRouteImport.update({
    id: '/principles/negative-space-programming',
    path: '/principles/negative-space-programming',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/examples/brandlens': typeof ExamplesBrandlensRoute
  '/principles/negative-space-programming': typeof PrinciplesNegativeSpaceProgrammingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/examples/brandlens': typeof ExamplesBrandlensRoute
  '/principles/negative-space-programming': typeof PrinciplesNegativeSpaceProgrammingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/examples/brandlens': typeof ExamplesBrandlensRoute
  '/principles/negative-space-programming': typeof PrinciplesNegativeSpaceProgrammingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/examples/brandlens' | '/principles/negative-space-programming'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/examples/brandlens' | '/principles/negative-space-programming'
  id:
    | '__root__'
    | '/'
    | '/examples/brandlens'
    | '/principles/negative-space-programming'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExamplesBrandlensRoute: typeof ExamplesBrandlensRoute
  PrinciplesNegativeSpaceProgrammingRoute: typeof PrinciplesNegativeSpaceProgrammingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/brandlens': {
      id: '/examples/brandlens'
      path: '/examples/brandlens'
      fullPath: '/examples/brandlens'
      preLoaderRoute: typeof ExamplesBrandlensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/principles/negative-space-programming': {
      id: '/principles/negative-space-programming'
      path: '/principles/negative-space-programming'
      fullPath: '/principles/negative-space-programming'
      preLoaderRoute: typeof PrinciplesNegativeSpaceProgrammingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExamplesBrandlensRoute: ExamplesBrandlensRoute,
  PrinciplesNegativeSpaceProgrammingRoute:
    PrinciplesNegativeSpaceProgrammingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
