/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExamplesBrandlensRouteImport } from './routes/examples.brandlens'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesBrandlensRoute = ExamplesBrandlensRouteImport.update({
  id: '/examples/brandlens',
  path: '/examples/brandlens',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/examples/brandlens': typeof ExamplesBrandlensRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/examples/brandlens': typeof ExamplesBrandlensRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/examples/brandlens': typeof ExamplesBrandlensRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/examples/brandlens'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/examples/brandlens'
  id: '__root__' | '/' | '/examples/brandlens'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExamplesBrandlensRoute: typeof ExamplesBrandlensRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/brandlens': {
      id: '/examples/brandlens'
      path: '/examples/brandlens'
      fullPath: '/examples/brandlens'
      preLoaderRoute: typeof ExamplesBrandlensRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExamplesBrandlensRoute: ExamplesBrandlensRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
